// AUTO-GENERATED by scripts/build-geo.mjs — do not edit.
export const SLUGS = [
  "ghana",
  "nigeria",
  "senegal",
  "kenya",
  "southAfrica",
  "egypt",
  "france",
  "germany",
  "italy",
  "spain",
  "unitedKingdom",
  "turkiye",
  "india",
  "china",
  "japan",
  "unitedStates",
  "mexico",
  "brazil",
  "argentina",
] as const;

export type Slug = (typeof SLUGS)[number];
